### ISSUE TITLE
Feature Request: ARM support

### ISSUE THREAD

**Issue by prestonvanloon** [kilic/bls12-381#2]
Opening this issue to request ARM64 build support or native go fallback. 

Tracking downstream here: https://github.com/prysmaticlabs/prysm/issues/2546
We may select between this library and phoreproject's BLS for ARM builds so we aren't totally blocked.

Thanks!

**Comment by kilic** [comment]
Native Go field implemntation is added. So now we have ARM support.

Native Go field implementation is generated by using [goff](https://hackmd.io/@zkteam/goff). Generated code edited according to [declarations](https://github.com/kilic/bls12-381/blob/master/arithmetic_decl.go) in order to fit in this library.
